export interface ChecklistItem {
  id: string;
  task: string;
  completed: boolean;
}

export interface ChecklistCategory {
  id: string;
  title: string;
  items: ChecklistItem[];
}

export const INITIAL_CHECKLIST: ChecklistCategory[] = [
  {
    id: "foundation",
    title: "1. Foundation & Setup",
    items: [
      { id: "f1", task: "WordPress installation", completed: false },
      { id: "f2", task: "SSL certificate setup", completed: false },
      { id: "f3", task: "Domain & hosting configuration", completed: false },
      { id: "f4", task: "CDN setup", completed: false },
      { id: "f5", task: "PHP version optimization", completed: false },
      { id: "f6", task: "Database optimization", completed: false },
      { id: "f7", task: "File permissions/security hardening", completed: false },
      { id: "f8", task: "Backup system setup", completed: false },
      { id: "f9", task: "Staging environment setup", completed: false },
      { id: "f10", task: "Child theme setup", completed: false },
      { id: "f11", task: "SMTP email configuration", completed: false },
      { id: "f12", task: "Basic legal pages setup", completed: false },
    ],
  },
  {
    id: "uiux",
    title: "2. UI/UX & Design",
    items: [
      { id: "ui1", task: "Custom homepage design", completed: false },
      { id: "ui2", task: "Responsive mobile-first design", completed: false },
      { id: "ui3", task: "Tablet optimization", completed: false },
      { id: "ui4", task: "Accessibility improvements (WCAG)", completed: false },
      { id: "ui5", task: "Typography system", completed: false },
      { id: "ui6", task: "Color system", completed: false },
      { id: "ui7", task: "Spacing system", completed: false },
      { id: "ui8", task: "Design consistency", completed: false },
      { id: "ui9", task: "CTA optimization", completed: false },
      { id: "ui10", task: "Conversion-focused sections", completed: false },
      { id: "ui11", task: "Animation/micro interactions", completed: false },
      { id: "ui12", task: "Bento/grid layouts", completed: false },
      { id: "ui13", task: "Dark/light mode (optional)", completed: false },
      { id: "ui14", task: "Custom iconography", completed: false },
      { id: "ui15", task: "Figma-to-WordPress implementation", completed: false },
      { id: "ui16", task: "Brand identity consistency", completed: false },
    ],
  },
  {
    id: "elementor",
    title: "3. Elementor Development",
    items: [
      { id: "el1", task: "Global styles setup", completed: false },
      { id: "el2", task: "Reusable templates", completed: false },
      { id: "el3", task: "Header builder", completed: false },
      { id: "el4", task: "Footer builder", completed: false },
      { id: "el5", task: "Mega menu", completed: false },
      { id: "el6", task: "Popup builder", completed: false },
      { id: "el7", task: "Theme builder", completed: false },
      { id: "el8", task: "Archive page templates", completed: false },
      { id: "el9", task: "Single post templates", completed: false },
      { id: "el10", task: "Dynamic content setup", completed: false },
      { id: "el11", task: "Motion effects optimization", completed: false },
      { id: "el12", task: "Custom breakpoints", completed: false },
      { id: "el13", task: "Form integrations", completed: false },
      { id: "el14", task: "Advanced responsive controls", completed: false },
    ],
  },
  {
    id: "seo",
    title: "4. SEO Optimization",
    items: [
      { id: "seo1", task: "Rank Math SEO setup", completed: false },
      { id: "seo2", task: "XML sitemap setup", completed: false },
      { id: "seo3", task: "Robots.txt optimization", completed: false },
      { id: "seo4", task: "Schema markup", completed: false },
      { id: "seo5", task: "Open Graph setup", completed: false },
      { id: "seo6", task: "Twitter Cards setup", completed: false },
      { id: "seo7", task: "SEO title/meta optimization", completed: false },
      { id: "seo8", task: "Focus keyword optimization", completed: false },
      { id: "seo9", task: "Internal linking structure", completed: false },
      { id: "seo10", task: "Breadcrumbs", completed: false },
      { id: "seo11", task: "Canonical URLs", completed: false },
      { id: "seo12", task: "Image SEO", completed: false },
      { id: "seo13", task: "Alt text optimization", completed: false },
      { id: "seo14", task: "Redirection setup", completed: false },
      { id: "seo15", task: "404 monitoring", completed: false },
      { id: "seo16", task: "Local SEO setup", completed: false },
      { id: "seo17", task: "Google indexing optimization", completed: false },
      { id: "seo18", task: "SEO-friendly permalink structure", completed: false },
    ],
  },
  {
    id: "performance",
    title: "5. Performance Optimization",
    items: [
      { id: "p1", task: "LiteSpeed Cache configuration", completed: false },
      { id: "p2", task: "CSS/JS minification", completed: false },
      { id: "p3", task: "Critical CSS generation", completed: false },
      { id: "p4", task: "Lazy loading", completed: false },
      { id: "p5", task: "Image compression", completed: false },
      { id: "p6", task: "WebP conversion", completed: false },
      { id: "p7", task: "Database cleanup", completed: false },
      { id: "p8", task: "Browser caching", completed: false },
      { id: "p9", task: "CDN optimization", completed: false },
      { id: "p10", task: "Core Web Vitals optimization", completed: false },
      { id: "p11", task: "Font optimization", completed: false },
      { id: "p12", task: "Preload critical assets", completed: false },
      { id: "p13", task: "Remove unused plugins/scripts", completed: false },
      { id: "p14", task: "Mobile performance optimization", completed: false },
    ],
  },
  {
    id: "security",
    title: "6. Security Setup",
    items: [
      { id: "s1", task: "Firewall setup", completed: false },
      { id: "s2", task: "Login protection", completed: false },
      { id: "s3", task: "Brute force protection", completed: false },
      { id: "s4", task: "Malware scanning", completed: false },
      { id: "s5", task: "Security headers", completed: false },
      { id: "s6", task: "Two-factor authentication", completed: false },
      { id: "s7", task: "Admin URL protection", completed: false },
      { id: "s8", task: "Spam protection", completed: false },
      { id: "s9", task: "Backup automation", completed: false },
      { id: "s10", task: "Activity logging", completed: false },
      { id: "s11", task: "User role permissions", completed: false },
      { id: "s12", task: "Disable XML-RPC", completed: false },
      { id: "s13", task: "File editing protection", completed: false },
    ],
  },
  {
    id: "accessibility",
    title: "7. Accessibility",
    items: [
      { id: "a1", task: "Elementor Accessibility improvements", completed: false },
      { id: "a2", task: "Keyboard navigation", completed: false },
      { id: "a3", task: "Proper heading hierarchy", completed: false },
      { id: "a4", task: "Contrast ratio optimization", completed: false },
      { id: "a5", task: "Focus states", completed: false },
      { id: "a6", task: "Screen reader compatibility", completed: false },
      { id: "a7", task: "ARIA labels", completed: false },
      { id: "a8", task: "Alt text implementation", completed: false },
      { id: "a9", task: "Accessible forms", completed: false },
      { id: "a10", task: "Semantic HTML structure", completed: false },
    ],
  },
  {
    id: "content",
    title: "8. Content & Blogging",
    items: [
      { id: "c1", task: "Blog category structure", completed: false },
      { id: "c2", task: "Tag structure", completed: false },
      { id: "c3", task: "Featured image system", completed: false },
      { id: "c4", task: "Author profile setup", completed: false },
      { id: "c5", task: "Newsletter integration", completed: false },
      { id: "c6", task: "Related posts", completed: false },
      { id: "c7", task: "Table of contents", completed: false },
      { id: "c8", task: "Reading progress bar", completed: false },
      { id: "c9", task: "Social sharing buttons", completed: false },
      { id: "c10", task: "Comment optimization", completed: false },
      { id: "c11", task: "Web Stories integration", completed: false },
      { id: "c12", task: "Blog SEO optimization", completed: false },
      { id: "c13", task: "Content templates", completed: false },
    ],
  },
  {
    id: "marketing",
    title: "9. Marketing & Lead Generation",
    items: [
      { id: "m1", task: "Newsletter forms", completed: false },
      { id: "m2", task: "Email marketing integration", completed: false },
      { id: "m3", task: "CTA sections", completed: false },
      { id: "m4", task: "Exit intent popups", completed: false },
      { id: "m5", task: "Lead capture forms", completed: false },
      { id: "m6", task: "WhatsApp integration", completed: false },
      { id: "m7", task: "Social proof/testimonials", completed: false },
      { id: "m8", task: "Conversion tracking", completed: false },
      { id: "m9", task: "Funnel optimization", completed: false },
      { id: "m10", task: "Landing page optimization", completed: false },
      { id: "m11", task: "Affiliate setup", completed: false },
      { id: "m12", task: "CRM integration", completed: false },
      { id: "m13", task: "Automation workflows", completed: false },
    ],
  },
  {
    id: "analytics",
    title: "10. Analytics & Tracking",
    items: [
      { id: "an1", task: "Site Kit by Google setup", completed: false },
      { id: "an2", task: "Google Analytics", completed: false },
      { id: "an3", task: "Google Search Console", completed: false },
      { id: "an4", task: "Google Tag Manager", completed: false },
      { id: "an5", task: "Event tracking", completed: false },
      { id: "an6", task: "Conversion tracking", completed: false },
      { id: "an7", task: "Heatmaps", completed: false },
      { id: "an8", task: "Scroll tracking", completed: false },
      { id: "an9", task: "UTM tracking", completed: false },
      { id: "an10", task: "Search performance monitoring", completed: false },
    ],
  },
  {
    id: "ecommerce",
    title: "11. E-commerce (Optional)",
    items: [
      { id: "ec1", task: "WooCommerce setup", completed: false },
      { id: "ec2", task: "Product page design", completed: false },
      { id: "ec3", task: "Cart optimization", completed: false },
      { id: "ec4", task: "Checkout optimization", completed: false },
      { id: "ec5", task: "Payment gateway setup", completed: false },
      { id: "ec6", task: "Shipping setup", completed: false },
      { id: "ec7", task: "GST/tax setup", completed: false },
      { id: "ec8", task: "Product schema", completed: false },
      { id: "ec9", task: "Wishlist", completed: false },
      { id: "ec10", task: "Coupons/offers", completed: false },
      { id: "ec11", task: "Order emails", completed: false },
      { id: "ec12", task: "Abandoned cart recovery", completed: false },
    ],
  },
  {
    id: "mobile",
    title: "12. Mobile Optimization",
    items: [
      { id: "mo1", task: "Mobile-first responsiveness", completed: false },
      { id: "mo2", task: "Touch-friendly UI", completed: false },
      { id: "mo3", task: "Mobile navigation optimization", completed: false },
      { id: "mo4", task: "Mobile speed optimization", completed: false },
      { id: "mo5", task: "AMP setup", completed: false },
      { id: "mo6", task: "PWA support (optional)", completed: false },
      { id: "mo7", task: "App-like interactions", completed: false },
    ],
  },
  {
    id: "qa",
    title: "14. Final QA & Launch",
    items: [
      { id: "qa1", task: "Cross-browser testing", completed: false },
      { id: "qa2", task: "Mobile testing", completed: false },
      { id: "qa3", task: "Speed testing", completed: false },
      { id: "qa4", task: "SEO audit", completed: false },
      { id: "qa5", task: "Broken link check", completed: false },
      { id: "qa6", task: "Form testing", completed: false },
      { id: "qa7", task: "Security audit", completed: false },
      { id: "qa8", task: "Accessibility audit", completed: false },
      { id: "qa9", task: "Backup verification", completed: false },
      { id: "qa10", task: "Final optimization", completed: false },
      { id: "qa11", task: "Google indexing request", completed: false },
      { id: "qa12", task: "Launch checklist", completed: false },
    ],
  },
];
